# Generated by Django 4.2 on 2023-04-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('image', models.ImageField(default='user/default/avtar.jpg', upload_to=users.utility.profile_img_path, verbose_name='Avatar photo')),
                ('cover', models.ImageField(default='user/default/cover.jpg', upload_to=users.utility.profile_img_path, verbose_name='Cover photo')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Address')),
                ('current_ip', models.CharField(blank=True, max_length=240, verbose_name='Current IP Address')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Book',
            },
        ),
    ]
