# Generated by Django 4.2 on 2023-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
